'use client'

import { createContext, useContext, useState, type ReactNode } from 'react'

type Language = 'en' | 'es'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.ourBoat': 'Our Boat',
    'nav.destinations': 'Destinations',
    'nav.faqs': 'FAQs',
    'nav.aboutUs': 'About Us',
    'nav.collaborations': 'Collaborations',
    'nav.calendar': 'Expeditions',
    'nav.blogs': 'Blogs',
    'nav.admin': 'Admin',
    'nav.contact': 'Contact',
    'nav.bookNow': 'Book Now',
    'nav.menu': 'Menu',
    'nav.signOut': 'Sign out',

    // Hero
    'hero.title': 'Quetzal',
    'hero.subtitle': 'THE GREATEST LIVEABOARD ADVENTURE IN THE OCEAN AWAITS YOU',
    
    // Hero
    'hero.button': 'View Calendar',
    
    // Experience Section
    'experience.title': 'What Awaits You Onboard',
    'experience.subtitle': 'Every moment aboard the Quetzal is an invitation to the extraordinary.',
    'experience.cta': 'Discover more',
    'experience.item1': 'Dive into the Unknown',
    'experience.item1Desc': 'Descend into a world few ever see. Every dive in Revillagigedo reveals something new — from volcanic seamounts to endless blue. Our expert divemasters guide you through the most spectacular sites in the archipelago.',
    'experience.item2': 'Swim with Giants',
    'experience.item2Desc': 'Share the water with graceful giant mantas, curious dolphins, and migrating whales. These encounters are not just sightings — they are moments that stay with you forever.',
    'experience.item3': 'Explore Untouched Shores',
    'experience.item3Desc': 'Between dives, discover remote beaches, hidden coves, and volcanic landscapes. The islands of Revillagigedo are as dramatic above water as they are below.',
    'experience.item4': 'Witness the Spectacle',
    'experience.item4Desc': 'Schools of hammerheads, whitetip reefs, silky sharks — the archipelago hosts some of the most dramatic marine congregations on Earth. Every dive is a front-row seat to nature at its wildest.',
    
    // Destination Section
    'destination.days': '7 DAYS OF EXPLORATION',
    'destination.title': 'SEA OF CORTEZ',
    'destination.year': '2026 STARTING AT',
    'destination.price': '$2,350 USD PER PERSON',
    'destination.cta': 'Ask Our Travel Expert',
    
    // Boat Gallery
    'boat.gallery.title': 'Our Boat',
    'boat.gallery.subtitle': 'Step aboard the Quetzal — a classic vessel designed for comfort, adventure, and unforgettable moments at sea.',
    'boat.gallery.staterooms': 'Staterooms',
    'boat.gallery.interior': 'Interior',
    
    // Marine Life Section
    'marine.title': 'This Is What You will See With Us',
    'marine.description': 'Join Quetzal\'s liveaboard adventure and witness breathtaking marine life—exactly what our guests see on this unforgettable underwater experience.',
    'marine.cta': 'See Upcoming Trips',
    
    // Destinations Grid
    'destinations.title': 'Our Destinations',
    'destinations.subtitle': 'Where Adventure Begins',
    'destinations.socorro.title': 'SOCORRO',
    'destinations.socorro.description': 'Born from volcanoes, Socorro is one of four islands that make up the Revillagigedo Archipelago. They sit in a unique geographical location that attracts some of the most incredible marine life in the world.',
    'destinations.magbay.title': 'MAG BAY + SOCORRO',
    'destinations.magbay.description': 'Embark on a 14-day liveaboard adventure from Los Cabos to Mag Bay and Socorro, diving with whales, sharks, and mantas daily.',
    'destinations.cortez.title': 'SEA OF CORTEZ',
    'destinations.cortez.description': 'Visit one of the most beautiful places on the planet, with days full of saltwater and sun, mountains, wildlife, culture, and history!',
    'destinations.explore': 'Explore Destination',
    
    // Upcoming Trips
    'trips.title': 'Upcoming Destination',
    'trips.subtitle': 'Guided by Experience Perfected by Passion',
    'trips.trip1.title': 'Magdalena Bay & Socorro Islands',
    'trips.trip1.dates': '16 OCT 2025 - 30 OCT 2025',
    'trips.trip1.price': 'from $5,199 USD per person',
    'trips.trip2.title': 'Socorro Islands (Revillagigedo)',
    'trips.trip2.dates': '06 JAN 2026 - 14 JAN 2026',
    'trips.trip2.price': 'from $3,500 USD per person',
    'trips.trip3.title': 'Sea of Cortez Trip',
    'trips.trip3.dates': '09 JUL 2026 - 16 JUL 2026',
    'trips.trip3.price': 'from $2,350 USD per person',
    'trips.details': 'Trip & Price Details',
    
    // Testimonials
    'testimonials.title': 'What Our Guests Say',
    'testimonials.subtitle': 'Don\'t just take our word for it—hear from divers who\'ve experienced the adventure of a lifetime',
    
    // Gallery
    'gallery.title': 'Captured Moments',
    'gallery.subtitle': 'Experience the beauty beneath the waves',
    'gallery.promise': 'This is what awaits you',
    'gallery.scrollHint': 'Scroll to discover',
    
    // Contact Form
    'contact.title': 'Plan Your Journey with Us',
    'contact.description': 'Use the form to contact our team — we\'re here to help you book and prepare for your Quetzal experience.',
    'contact.email': 'E-mail:',
    'contact.name': 'Name',
    'contact.emailField': 'Email',
    'contact.destinations': 'Destinations',
    'contact.message': 'Message',
    'contact.submit': 'Submit',
    'contact.required': 'Fields marked with an * are required',
    'contact.success': 'Thank you! We\'ll be in touch soon.',
    'contact.error': 'Something went wrong. Please try again.',

    // Footer
    'footer.brand': 'Experience the greatest liveaboard adventure in the Pacific Ocean. Diving expeditions to Mexico\'s most extraordinary destinations.',
    'footer.destinations': 'Destinations',
    'footer.socorro': 'Socorro Islands',
    'footer.cortez': 'Sea of Cortez',
    'footer.magBay': 'Magdalena Bay',
    'footer.company': 'Company',
    'footer.contactForm': 'Contact Form',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cancellation': 'Cancellation Policy',
    'footer.divingRisks': 'Diving Risks',

    // Our Boat Page
    'boat.hero': 'Meet the Quetzal',
    'boat.subtitle': 'A classic luxury vessel designed for exploration, comfort, and unforgettable moments on the open sea.',
    'boat.specs.title': 'Vessel Specifications',
    'boat.specs.length': 'Length',
    'boat.specs.lengthVal': '120 ft (36.5 m)',
    'boat.specs.beam': 'Beam',
    'boat.specs.beamVal': '24 ft (7.3 m)',
    'boat.specs.guests': 'Guests',
    'boat.specs.guestsVal': 'Up to 20',
    'boat.specs.cabins': 'Cabins',
    'boat.specs.cabinsVal': '10 Private',
    'boat.specs.speed': 'Cruising Speed',
    'boat.specs.speedVal': '10 knots',
    'boat.specs.compressor': 'Compressors',
    'boat.specs.compressorVal': '2x Bauer',
    'boat.comfort.title': 'Comfort Onboard',
    'boat.comfort.subtitle': 'Every detail is designed so you can focus on what matters — the adventure.',
    'boat.comfort.dining': 'Gourmet Dining',
    'boat.comfort.diningDesc': 'Freshly prepared meals with local seafood and international cuisine, paired with fine wines and cold beverages.',
    'boat.comfort.sunDeck': 'Sun Deck & Lounge',
    'boat.comfort.sunDeckDesc': 'A spacious top deck with lounge chairs and shade areas, perfect for sunset cocktails between dives.',
    'boat.comfort.cabin': 'Private Cabins',
    'boat.comfort.cabinDesc': 'Comfortable cabins with air conditioning, private bathrooms, and ample storage for your gear.',
    'boat.comfort.dive': 'Dive Platform',
    'boat.comfort.diveDesc': 'A purpose-built dive deck with individual gear stations, camera rinse tanks, and warm showers.',

    // Destination Pages
    'dest.hero': 'Explore Our',
    'dest.heroHighlight': 'Destinations',
    'dest.backAll': 'View All Destinations',
    'dest.fromPrice': 'Starting from',
    'dest.perPerson': 'per person',
    'dest.duration': 'Duration',
    'dest.nextDeparture': 'Next Departure',
    'dest.bookNow': 'Book This Trip',
    'dest.calendar': 'Seasonal Wildlife Calendar',

    // Socorro
    'socorro.title': 'Socorro Islands',
    'socorro.subtitle': 'The Galápagos of Mexico',
    'socorro.description1': 'The Revillagigedo Archipelago, known as the Socorro Islands, is a UNESCO World Heritage Site located 250 miles south of Cabo San Lucas. These volcanic islands rise from the deep ocean, creating a unique ecosystem that attracts some of the largest marine species on Earth.',
    'socorro.description2': 'From giant oceanic mantas with wingspans over 20 feet to schools of hammerhead sharks, bottlenose dolphins, and seasonal humpback whale encounters — Socorro delivers world-class diving that rivals the best on the planet.',
    'socorro.highlights': 'What You\'ll See',
    'socorro.h1': 'Giant Oceanic Mantas',
    'socorro.h1d': 'Witness mantas with wingspans over 20 feet glide gracefully through crystal-clear waters, often approaching divers with gentle curiosity.',
    'socorro.h2': 'Hammerhead Schools',
    'socorro.h2d': 'Dive among hundreds of scalloped hammerhead sharks gathering at cleaning stations, an awe-inspiring sight unique to these waters.',
    'socorro.h3': 'Humpback Whales',
    'socorro.h3d': 'Between January and April, humpback whales visit these waters. Hear their songs underwater and witness spectacular breaches.',
    'socorro.h4': 'Dolphins & Large Pelagics',
     'socorro.h4d': 'Playful bottlenose dolphins frequently approach divers, while tuna, wahoo, and other large pelagics patrol the blue.',
    'socorro.h5': 'Tiger & Silky Sharks',
    'socorro.h5d': 'Oceanic predators including tiger sharks, silky sharks, and oceanic white-tips patrol the deep blue waters around these volcanic islands.',
    'socorro.h6': 'Whale Sharks & False Orcas',
    'socorro.h6d': 'Whale sharks visit in November, December, and May. May also brings giant bait balls and pods of false orcas.',
    'socorro.diveSites.title': 'Dive Sites',
    'socorro.diveSites.sanBenedicto.boiler.name': 'The Boiler',
    'socorro.diveSites.sanBenedicto.boiler.description': 'A submerged seamount rising from the ocean floor to about 50m — a renowned manta cleaning station where giants gather.',
    'socorro.diveSites.sanBenedicto.boiler.fauna': 'Giant oceanic mantas (up to 6m+), bottlenose dolphins, amberjack, big eye jacks, black jacks, yellowfin tuna',
    'socorro.diveSites.sanBenedicto.canyon.name': 'The Canyon',
    'socorro.diveSites.sanBenedicto.canyon.description': 'Large mantas wander this site — 4m+ wingspans circling overhead. Humpback whale songs are often audible underwater.',
    'socorro.diveSites.sanBenedicto.canyon.fauna': 'Giant mantas, black mantas, humpback whales (songs), whale sharks',
    'socorro.diveSites.rocaPartida.rocaPartida.name': 'Roca Partida',
    'socorro.diveSites.rocaPartida.rocaPartida.description': 'A huge reef towering in the middle of the open ocean with 70-80m walls. So remote it takes 6 hours by ship from San Benedicto.',
    'socorro.diveSites.rocaPartida.rocaPartida.fauna': 'Schooling hammerhead sharks (hundreds), silver-tip sharks, black jacks, tiger sharks, whale sharks, Galapagos sharks',
    'socorro.diveSites.socorroIsland.caboPearce.name': 'Cabo Pearce',
    'socorro.diveSites.socorroIsland.caboPearce.description': 'A seamount stretching toward the open sea off Socorro Island. Multiple big-creature encounters on every dive.',
    'socorro.diveSites.socorroIsland.caboPearce.fauna': 'Bottlenose dolphins, hammerhead sharks, Galapagos sharks, silver-tip sharks, giant mantas (predation scenes), humpback whales',
    'socorro.calendar.jan': 'Humpback whales, giant mantas, hammerhead sharks, bottlenose dolphins',
    'socorro.calendar.feb': 'Humpback whales (peak), giant mantas, hammerhead sharks, bottlenose dolphins',
    'socorro.calendar.mar': 'Humpback whales (peak), giant mantas, hammerhead sharks, bottlenose dolphins',
    'socorro.calendar.apr': 'Humpback whales, giant mantas, hammerhead sharks, bottlenose dolphins',
    'socorro.calendar.may': 'Giant mantas, hammerhead sharks, dolphins, whale sharks, false orcas, giant bait balls',
    'socorro.calendar.jun': 'Giant mantas, hammerhead sharks, bottlenose dolphins',
    'socorro.calendar.jul': 'Giant mantas, hammerhead sharks, bottlenose dolphins',
    'socorro.calendar.nov': 'Giant mantas, hammerhead sharks, bottlenose dolphins, whale sharks',
    'socorro.calendar.dec': 'Giant mantas, hammerhead sharks, bottlenose dolphins, whale sharks',
    'socorro.conservation.unesco': 'UNESCO World Heritage Site',
    'socorro.conservation.protectedArea': 'Revillagigedo Archipelago National Park',
    'socorro.conservation.designation': 'Designated in 2016',
    'socorro.gallery.title': 'Gallery',
    'socorro.gallery.images': '[{"src":"/images/panoramicas/Isla Socorro.webp","alt":"Volcanic cliffs of Socorro Island rising from the Pacific"},{"src":"/images/panoramicas/Manta el Boiler 1.webp","alt":"Giant oceanic manta at The Boiler cleaning station"},{"src":"/images/panoramicas/Cabo Pearce .webp","alt":"Dramatic seascape at Cabo Pearce dive site"},{"src":"/images/panoramicas/Clariones.webp","alt":"The remote volcanic island of Clarion"},{"src":"/images/panoramicas/Pargos Roca.webp","alt":"School of snappers swarming Roca Partida"},{"src":"/images/panoramicas/Delfin Kike.webp","alt":"Bottlenose dolphins riding the bow wave"}]',

    // Sea of Cortez
    'cortez.title': 'Sea of Cortez',
    'cortez.subtitle': 'The Aquarium of the World',
    'cortez.description1': 'Jacques Cousteau called the Sea of Cortez "the aquarium of the world," and for good reason. This narrow body of water between the Baja California peninsula and mainland Mexico is one of the most biodiverse marine environments on the planet.',
    'cortez.description2': 'Over 900 species of fish, thousands of invertebrates, and one-third of the world\'s cetacean species call these waters home. From sea lion colonies to whale watching, from colorful nudibranchs to massive whale sharks — the Sea of Cortez delivers diversity unmatched anywhere.',
    'cortez.highlights': 'What You\'ll See',
    'cortez.h1': 'Sea Lion Colonies',
    'cortez.h1d': 'Play with curious sea lions at Espíritu Santo Island — they love to twirl, spin, and blow bubbles around delighted divers.',
    'cortez.h2': 'Whale Sharks',
    'cortez.h2d': 'Swim alongside the world\'s largest fish in the nutrient-rich waters of Bahía de La Paz, a truly humbling experience.',
    'cortez.h3': 'Colorful Reef Life',
    'cortez.h3d': 'Vibrant nudibranchs, moray eels, octopus, and over 700 species of reef fish make every dive a treasure hunt.',
    'cortez.h4': 'Stunning Topside',
    'cortez.h4d': 'Dramatic desert landscapes, secluded coves, and mountainous islands create breathtaking scenery above and below water.',
    'cortez.h5': 'Mobula Rays',
    'cortez.h5d': 'From July through October, mobula rays gather in the thousands at Punta Lobo — jumping, rolling, and packing the water from surface to seafloor.',
    'cortez.h6': 'Macro Life & Wrecks',
    'cortez.h6d': 'Bluespotted Jawfish, Signal blennies, giant jawfishes, nudibranchs — and the 80-meter Salvatierra ferry wreck teeming with oversized reef fish.',
    'cortez.diveSites.title': 'Dive Sites',
    'cortez.diveSites.laPazBay.losIslotes.name': 'Los Islotes',
    'cortez.diveSites.laPazBay.losIslotes.description': 'A rocky islet home to a colony of over 400 California sea lions. Pups start playing with divers in September — they nibble fins and snorkels in the south-side cave.',
    'cortez.diveSites.laPazBay.losIslotes.fauna': '400+ California sea lions, Bluespotted Jawfish, sardine schools, mobula rays, Mexican barracudas, gobies, nudibranchs',
    'cortez.diveSites.laPazBay.laPazBay.name': 'La Paz Bay',
    'cortez.diveSites.laPazBay.laPazBay.description': "The bay has become a reliable place to swim with whale sharks — the world's largest fish — in their natural feeding grounds.",
    'cortez.diveSites.laPazBay.laPazBay.fauna': 'Whale sharks',
    'cortez.diveSites.laPazBay.swanneeReef.name': 'Swannee Reef',
    'cortez.diveSites.laPazBay.swanneeReef.description': 'An isolated reef in a white sand area — a fish paradise. Signal blennies pop out of holes, flashing their dorsal fins three times before retreating.',
    'cortez.diveSites.laPazBay.swanneeReef.fauna': 'Mexican goatfish, Spottail grunt, Signal blennies, barracudas, skip jacks, sea lions (occasional)',
    'cortez.diveSites.laPazBay.salvatierra.name': 'Salvatierra Wreck',
    'cortez.diveSites.laPazBay.salvatierra.description': 'An 80-meter ferry sunk at about 20m depth, almost completely intact. It has become a thriving artificial reef.',
    'cortez.diveSites.laPazBay.salvatierra.fauna': 'Unusually large grunts and angelfish, reef fish',
    'cortez.diveSites.laPazBay.elCorralito.name': 'El Corralito',
    'cortez.diveSites.laPazBay.elCorralito.description': 'Known for its uniquely giant jawfishes — noticeably larger than anywhere else in the Sea of Cortez.',
    'cortez.diveSites.laPazBay.elCorralito.fauna': 'Giant jawfishes',
    'cortez.diveSites.northernIslands.elBajo.name': 'El Bajo',
    'cortez.diveSites.northernIslands.elBajo.description': 'Three seamounts with pinnacles at 18-22m. Drift dives through hundreds of hammerheads snaking their heads and bodies past you.',
    'cortez.diveSites.northernIslands.elBajo.fauna': 'Hammerhead sharks (hundreds, adults and juveniles), bonitos, skip jacks, marlin, whale sharks',
    'cortez.diveSites.northernIslands.whaleIsland.name': 'Whale Island',
    'cortez.diveSites.northernIslands.whaleIsland.description': 'A precipitous island shaped like a whale. Caves on the southwest side lead to the north through seafan-filled passages.',
    'cortez.diveSites.northernIslands.whaleIsland.fauna': 'Cortez angelfish, seafans, reef fish',
    'cortez.diveSites.northernIslands.sanFrancisquito.name': 'San Francisquito',
    'cortez.diveSites.northernIslands.sanFrancisquito.description': 'A dive site only reachable by liveaboard. Without the territorial competition of busier sites, the sea lions here are calmer and more relaxed.',
    'cortez.diveSites.northernIslands.sanFrancisquito.fauna': 'California sea lions (calm, relaxed), reef fish',
    'cortez.diveSites.eastCape.lasAnimas.name': 'Las Ánimas',
    'cortez.diveSites.eastCape.lasAnimas.description': 'Only accessible by liveaboard. Giant diamond stingrays glide among colorful seafans while big eye trevallies swirl around.',
    'cortez.diveSites.eastCape.lasAnimas.fauna': 'Longnose hawkfish, giant diamond stingrays, seafans, big eye trevallies, hammerhead sharks, sea turtles',
    'cortez.diveSites.eastCape.caboPulmo.name': 'Cabo Pulmo / Gordo Banks',
    'cortez.diveSites.eastCape.caboPulmo.description': "Eight miles offshore at depths up to 40m with powerful currents — for advanced divers only. One of the region's top dive spots.",
    'cortez.diveSites.eastCape.caboPulmo.fauna': 'Large schools of jacks, bull sharks, reef fish',
    'cortez.calendar.aug': 'Whale sharks, hammerhead sharks, mobula rays (season starts), sea lions',
    'cortez.calendar.sep': 'Whale sharks, hammerhead sharks, mobula rays (peak — thousands), sea lions (pups start playing with divers)',
    'cortez.calendar.oct': 'Whale sharks, hammerhead sharks, mobula rays (peak), sea lions',
    'cortez.calendar.nov': 'Sea lions (high activity), hammerhead sharks, whale sharks (fading), mobula rays',
    'cortez.conservation.unesco': 'UNESCO World Heritage Site',
    'cortez.conservation.protectedArea': 'Islands and Protected Areas of the Gulf of California',
    'cortez.conservation.designation': 'Designated in 2005',
    'cortez.gallery.title': 'Gallery',
    'cortez.gallery.images': '[{"src":"/images/panoramicas/PuntaTosca.webp","alt":"Rugged coastline of Punta Tosca, Baja California Sur"},{"src":"/images/panoramicas/loreto-magdalena-bay.webp","alt":"Pristine waters of Loreto and Magdalena Bay"},{"src":"/images/panoramicas/ROca Partida .webp","alt":"The iconic pinnacle of Roca Partida in open ocean"},{"src":"/images/panoramicas/Quetzal San Bene.webp","alt":"The Quetzal anchored off San Benedicto Island"},{"src":"/images/panoramicas/Manta Clariones.webp","alt":"Manta ray gliding through crystal-clear waters"}]',

    // Magdalena Bay
    'magbay.title': 'Bahía Magdalena',
    'magbay.subtitle': 'Where Whales Meet the Desert',
    'magbay.description1': 'Bahía Magdalena is one of Baja California\'s best-kept secrets. This vast protected lagoon on the Pacific coast is famous worldwide as a nursery for gray whales, who travel over 10,000 miles to calve in its warm, shallow waters.',
    'magbay.description2': 'Combined with a journey to Socorro, this expedition offers the rare chance to experience both the intimacy of close whale encounters in the bay and the adrenaline of big-animal diving at the archipelago — two截然不同的 worlds in one unforgettable trip.',
    'magbay.highlights': 'What You\'ll See',
    'magbay.h1': 'Gray Whale Encounters',
    'magbay.h1d': 'Get within arm\'s reach of gentle gray whales and their calves — one of the most profound wildlife experiences anywhere.',
    'magbay.h2': 'Mangrove Channels',
    'magbay.h2d': 'Kayak through pristine mangrove channels teeming with birds, rays, and tropical fish in crystal-clear shallows.',
    'magbay.h3': 'Desert Wildlife',
    'magbay.h3d': 'Spot coyotes, osprey, and desert foxes along the unspoiled dunes and remote beaches of Isla Magdalena.',
    'magbay.h4': 'Socorro Diving',
    'magbay.h4d': 'The second half brings mantas, sharks, and dolphins at the Revillagigedo Archipelago — the best of both worlds.',
    'magbay.h5': 'Mexico Sardine Run',
    'magbay.h5d': 'From October through December, the Pacific side of Baja explodes with life during the annual sardine run — attracting striped marlin, seabirds, and cetaceans in spectacular feeding frenzies.',
    'magbay.h6': '14-Day Expedition',
    'magbay.h6d': 'Two worlds in one unforgettable trip: the intimacy of close whale encounters in the bay, followed by big-animal diving with mantas, sharks, and dolphins at the Revillagigedo Archipelago.',
    'magbay.calendar.jan': 'Gray whales (peak), mothers and calves in the lagoon',
    'magbay.calendar.feb': 'Gray whales (peak), intimate close encounters',
    'magbay.calendar.mar': 'Gray whales (peak), mothers and calves',
    'magbay.calendar.apr': 'Gray whales (final weeks)',
    'magbay.calendar.oct': 'Sardine run begins — striped marlin, seabirds, cetaceans',
    'magbay.calendar.nov': 'Sardine run (peak), Pacific explosion of life',
    'magbay.calendar.dec': 'Sardine run, massive bait balls',
    'magbay.conservation.unesco': 'UNESCO Whale Sanctuary',
    'magbay.conservation.protectedArea': 'Bahía Magdalena Protected Lagoon',
    'magbay.conservation.designation': 'Part of the UNESCO World Heritage Site',
    'magbay.gallery.title': 'Gallery',
    'magbay.gallery.images': '[{"src":"/images/panoramicas/loreto-magdalena-bay.webp","alt":"The protected lagoon of Bahía Magdalena at sunset"},{"src":"/images/panoramicas/Puntas blancas 1.webp","alt":"Whitetip reef sharks resting on the sandy bottom"},{"src":"/images/panoramicas/Puntas blancas 4.webp","alt":"Curious whitetip sharks patrolling the reef"},{"src":"/images/panoramicas/Puntas blancas Balcón.webp","alt":"Panoramic view from the Balcón dive site"}]',

    // FAQ Page
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Everything you need to know before your expedition.',
    'faq.booking.title': 'Booking & Reservations',
    'faq.q1': 'How do I book a trip?',
    'faq.a1': 'You can book directly through our contact form, send us an email, or contact our travel experts who will help you find the perfect expedition for your dates and interests.',
    'faq.q2': 'What is the cancellation policy?',
    'faq.a2': 'Cancellations made more than 120 days before departure receive a full refund minus a $200 processing fee. Between 60–120 days, 50% refund. Less than 60 days, no refund. We strongly recommend travel insurance.',
    'faq.q3': 'Do you offer group discounts?',
    'faq.a3': 'Yes! Groups of 6 or more receive a 10% discount. For larger groups or charter inquiries, please contact us directly for custom pricing.',
    'faq.preparation.title': 'Preparation & Packing',
    'faq.q4': 'What certification level do I need?',
    'faq.a4': 'Most dives require an Open Water certification with at least 25 logged dives. For Socorro, we recommend Advanced Open Water due to currents and depth. Non-divers are also welcome for snorkeling and topside activities.',
    'faq.q5': 'What should I pack?',
    'faq.a5': 'We provide a detailed packing list upon booking. Essentials include: reef-safe sunscreen, motion sickness medication, 3mm wetsuit (5mm for winter), dive computer, and a camera if you have one.',
    'faq.q6': 'Do I need travel insurance?',
    'faq.a6': 'We strongly recommend comprehensive travel insurance including dive evacuation coverage (DAN membership). This protects you against trip cancellations, medical emergencies, and evacuation scenarios.',
    'faq.onboard.title': 'Onboard Experience',
    'faq.q7': 'What are the cabins like?',
    'faq.a7': 'All cabins are private with air conditioning, en-suite bathrooms, 110V outlets, and storage space. Categories range from Standard to Master Suite. All linens and towels are provided.',
    'faq.q8': 'How many dives per day?',
    'faq.a8': 'Typically 3–4 dives per day including a night dive when conditions allow. Dive schedules are flexible and weather-dependent.',
    'faq.q9': 'What about dietary restrictions?',
    'faq.a9': 'Our chef can accommodate most dietary needs including vegetarian, vegan, gluten-free, and kosher. Please inform us at least 2 weeks before departure.',

    // About Page
    'about.title': 'Your Ocean Story Starts Here',
    'about.subtitle': 'Where adventure meets tranquility — and you\'re the hero.',
    'about.story': 'Your Journey Begins',
    'about.storyText1': 'You wake to the sound of the sea — the gentle roll of the boat, salt in the air, and the first light spilling over the horizon.',
    'about.storyText2': 'This isn\'t a tour. It\'s your expedition. From the moment you step aboard, every rhythm of the day revolves around your experience — your dives, your pace, your connection with the ocean.',
    'about.storyText3': 'You\'ll explore remote marine ecosystems few people ever see. Giant mantas that glide past you in Socorro. Whale sharks in the Sea of Cortez. Reefs teeming with life where your only audience is the sea itself.',
    'about.storyText4': 'With small groups and a crew that knows your name by breakfast, you\'ll never feel like a passenger number. Your comfort, your curiosity, and your sense of wonder come first.',
    'about.storyText5': 'Fresh meals prepared for your taste, private cabins designed for your rest, and decks built for your stories at sunset. Every detail exists so you can focus on what matters: the dive, the moment, the memory.',
    'about.storyText6': 'This is your ocean. Your adventure. Your story — and it starts here.',
    'about.values': 'What You\'ll Experience',
    'about.v1': 'Respect for the Ocean',
    'about.v1d': 'You\'ll experience the ocean not as a backdrop, but as a living world. Every dive is guided by a deep respect for marine ecosystems — so you connect with nature responsibly and meaningfully.',
    'about.v2': 'Authentic Exploration',
    'about.v2d': 'Your trip isn\'t a scripted itinerary. You\'ll discover wild places on their own terms, guided by people who know every current and cove — and who want you to feel the thrill of true exploration.',
    'about.v3': 'Personal Connection',
    'about.v3d': 'From the moment you board, you\'re family. You\'ll share meals, stories, and sunsets with a crew and fellow divers who share your passion. It\'s not just service — it\'s genuine human connection.',
    'about.v5': 'Tailored to You',
    'about.v5d': 'Small groups mean your experience adapts to you — not the other way around. Flexible dive schedules, personalized attention, and quiet corners when you just want to watch the sea.',
    'about.cta': 'Ready to Write Your Own Ocean Story?',
    'about.ctaButton': 'Start Your Adventure',
    'about.socialProof': '+500 divers have lived this experience',

    // Collaborations Page
    'collab.title': 'Our Collaborations',
    'collab.subtitle': 'Working together for a healthier ocean.',
    'collab.intro': 'We believe in the power of partnership. Our collaborations span marine research, conservation, and community development — ensuring that every expedition gives back to the ocean and the people who depend on it.',
    'collab.p1.name': 'Sylvia Earle Alliance',
    'collab.p1.desc': 'Supporting Mission Blue Hope Spots in the Revillagigedo Archipelago and Sea of Cortez, contributing data to global marine conservation efforts.',
    'collab.p2.name': 'PADI Conservation',
    'collab.p2.desc': 'Official PADI AWARE partner. We conduct reef health surveys, debris cleanups, and help certify new divers in conservation practices.',
    'collab.p3.name': 'Local Fishing Co-ops',
    'collab.p3.desc': 'We source our seafood from sustainable local co-ops and provide alternative income opportunities through eco-tourism training.',
    'collab.p4.name': 'CICIMAR Research',
    'collab.p4.desc': 'Collaborating with Mexico\'s Center for Scientific Research and Higher Education to monitor whale populations and ocean health.',
    'collab.cta': 'Interested in partnering with us?',
    'collab.ctaButton': 'Get In Touch',

    // Testimonials Page
    'testimonials.pageTitle': 'Guest Testimonials',
    'testimonials.pageSubtitle': 'Real stories from real adventurers.',
    'testimonials.all': 'All Trips',
    'testimonials.socorro': 'Socorro',
    'testimonials.cortez': 'Sea of Cortez',
    'testimonials.magBay': 'Mag Bay',

    // Blog Page
    'blog.title': 'The Quetzal Journal',
    'blog.subtitle': 'Stories, guides, and insights from the Mexican Pacific.',
    'blog.readMore': 'Read More',
    'blog.comingSoon': 'Coming Soon',
    'blog.comingSoonDesc': 'We\'re preparing amazing stories about our expeditions, marine life encounters, and travel guides. Stay tuned!',
    'blog.category': 'Category',
    'blog.catAll': 'All',
    'blog.catExpeditions': 'Expeditions',
    'blog.catMarine': 'Marine Life',
    'blog.catGuides': 'Travel Guides',
    'blog.catConservation': 'Conservation',
    'blog.back': 'Back to Blog',
    'blog.empty': 'No Posts Yet',
    'blog.emptyDesc': 'Check back soon for stories and updates from our expeditions.',

    // Contact Page
    'contact.pageTitle': 'Get In Touch',
    'contact.pageSubtitle': 'Ready to embark on the adventure of a lifetime? We\'re here to help.',
    'contact.phone': 'Phone',
    'contact.phoneVal': '+52 624 123 4567',
    'contact.hours': 'Hours',
    'contact.hoursVal': 'Mon–Sat, 9am–6pm MT',
    'contact.location': 'Location',
    'contact.locationVal': 'Cabo San Lucas, BCS, México',
    'contact.social': 'Follow Us',

    // Shared
    'shared.backHome': 'Back to Home',

    // Nav dropdown
    'nav.socorro': 'Socorro Islands',
    'nav.cortez': 'Sea of Cortez',
    'nav.magbay': 'Magdalena Bay',

    // Legal
    'privacy.title': 'Privacy Policy',
    'privacy.content': 'We are committed to protecting your privacy. This policy outlines how we collect, use, and protect your personal information when you use our website and book our services. For the full privacy policy, please contact us directly.',
    'terms.title': 'Terms of Service',
    'terms.content': 'By using our website and booking our services, you agree to these terms. All bookings are subject to our cancellation policy. For complete terms and conditions, please contact us directly.',

    // Booking Page
    'booking.title': 'Book Your Expedition',
    'booking.steps.login': 'Login',
    'booking.steps.selectCruise': 'Select Cruise',
    'booking.steps.payment': 'Payment',
    'booking.flow.back': 'Back',
    'booking.flow.next': 'Next',
    'booking.login.title': 'Login to Your Account',
    'booking.login.email': 'Email',
    'booking.login.password': 'Password',
    'booking.login.submit': 'Login',
    'booking.login.error': 'Invalid email or password',
    'booking.login.invalid': 'Please enter a valid email address',
    'booking.register.title': 'Create Your Account',
    'booking.register.name': 'Full Name',
    'booking.register.email': 'Email',
    'booking.register.password': 'Password',
    'booking.register.confirmPassword': 'Confirm Password',
    'booking.register.submit': 'Create Account',
    'booking.register.passwordMismatch': 'Passwords do not match',
    'booking.register.invalid': 'Please fill in all fields',
    'booking.register.loginTab': 'Sign In',
    'booking.register.registerTab': 'Register',
    'booking.cruise.title': 'Select Your Cruise',
    'booking.cruise.select': 'Select',
    'booking.cruise.signIn': 'Sign in',
    'booking.cruise.selected': 'Selected',
    'booking.cruise.departure': 'Departure',
    'booking.cruise.route': 'Route',
    'booking.cruise.pricePerPerson': 'per person',
    'booking.cruise.boat': 'Ship',
    'booking.cruise.tripDetails': 'Trip & Price details',
    'booking.cruise.dives': 'dive days',
    'booking.cruise.embarkation': 'Embarkation',
    'booking.guest.title': 'Number of Guests',
    'booking.guest.label': 'Guests',
    'booking.guest.capacity': 'Capacity: 18 max',
    'booking.guest.increment': 'Add guest',
    'booking.guest.decrement': 'Remove guest',
    'booking.guest.minReached': 'Minimum 1 guest required',
    'booking.guest.maxReached': 'Maximum 18 guests allowed',
    'booking.payment.title': 'Complete Your Booking',
    'booking.payment.summary': 'Booking Summary',
    'booking.payment.cruise': 'Cruise',
    'booking.payment.guests': 'Guests',
    'booking.payment.total': 'Total',
    'booking.payment.payWithCard': 'Pay with Credit Card',
    'booking.payment.payWithPaypal': 'Pay with PayPal',
    'booking.payment.payWithBank': 'Pay with Bank Transfer',
    'booking.payment.confirming': 'Processing...',
    'booking.payment.success': 'Booking confirmed! We will contact you shortly.',
    'booking.confirmation.title': 'Booking Confirmed',
    'booking.confirmation.message': 'Thank you for your booking. Our team will be in touch with next steps.',
    'booking.confirmation.backHome': 'Back to Home',

    // Booking Info Cards
    'booking.info.types': 'Reservation Types',
    'booking.info.individual': 'Individual Pass',
    'booking.info.individualDesc': 'Reserve your spot on our shared expeditions. Choose from three comfort tiers: Basic ($2,500), Standard ($3,000), or Premium ($3,500). Up to 18 passengers per trip.',
    'booking.info.half': 'Half Charter',
    'booking.info.halfDesc': 'Book as a group and save. For every 8 paid spaces, receive 1 complimentary spot. Ideal for dive clubs, families, and groups of friends.',
    'booking.info.full': 'Full Charter',
    'booking.info.fullDesc': 'Your expedition, your way. Private charter for your exclusive group with a fully customized itinerary. Contact us for a personalized quote.',
    'booking.info.how': 'How It Works',
    'booking.info.choose': 'Choose Your Expedition',
    'booking.info.chooseDesc': 'Browse our curated itineraries to Socorro Islands, Sea of Cortez, and Magdalena Bay. Each trip offers unique marine encounters.',
    'booking.info.signin': 'Sign In or Register',
    'booking.info.signinDesc': 'Create your account or log in to continue. Your information is saved for a faster booking experience next time.',
    'booking.info.guests': 'Select Your Guests',
    'booking.info.guestsDesc': 'Tell us how many adventurers will join you. Solo traveler, couple, or group — we have space for everyone.',
    'booking.info.confirm': 'Confirm & Pay',
    'booking.info.confirmDesc': 'Review your selection, complete the payment, and receive your booking confirmation instantly via email.',

    // Tier Pricing Keys
    'booking.tier.basic': 'Basic',
    'booking.tier.standard': 'Standard',
    'booking.tier.premium': 'Premium',
    'booking.tier.selectHint': 'Select a pricing tier to continue',
    'booking.tier.selected': 'Tier selected',
    'booking.payment.freeSpaces': 'Free spaces',
    'booking.payment.paidSpaces': 'Paid spaces',
    'booking.payment.tierPrice': 'per person (tier)',
    'booking.fullCharter.label': 'Private Charter',
    'booking.fullCharter.description': 'Want the whole boat to yourself? Contact us for a custom itinerary and pricing.',
    'booking.fullCharter.cta': 'Contact Us',
    'booking.confirmation.tier': 'Pricing Tier',
    'booking.confirmation.freeSpaces': 'Free Spaces (Half Charter)',

    // Account Page
    'account.title': 'My Account',
    'account.welcome': 'Welcome, {name}',
    'account.profile': 'Profile',
    'account.reservations': 'Reservation History',
    'account.save': 'Save',
    'account.edit': 'Edit',
    'account.name': 'Name',
    'account.email': 'Email',
    'account.phone': 'Phone',
    'account.noReservations': 'No reservations yet',
    'account.saveSuccess': 'Profile updated successfully',
    'account.status.pending': 'Pending',
    'account.status.confirmed': 'Confirmed',
    'account.status.completed': 'Completed',

    // Reservation Status
    'reservation.status.pending': 'Pending Approval',
    'reservation.status.confirmed': 'Confirmed',
    'reservation.status.expired': 'Expired',
    'reservation.status.cancelled': 'Cancelled',

    // Account Panel
    'account.reservations.title': 'My Reservations',
    'account.reservations.empty': 'No reservations yet. Start by booking an expedition!',
    'account.reservations.loading': 'Loading reservations...',
    'account.reservations.error': 'Failed to load reservations',

    // Reservation Actions
    'reservation.actions.downloadPdf': 'Download PDF',
    'reservation.actions.emailReceipt': 'Send via Email',
    'reservation.actions.whatsappReceipt': 'Send via WhatsApp',
    'reservation.actions.holdExpires': 'Hold expires: {date}',
    'reservation.actions.expiredMessage': 'This reservation has expired and the date has been released.',

    // Payment Section
    'booking.payment.processing': 'Processing...',
    'booking.payment.error': 'Payment failed. Please try again.',
    'booking.payment.dateBlocked': 'This date is no longer available. Please select another.',
    'booking.payment.authRequired': 'Please log in to complete your booking.',

    // Confirmation
    'booking.confirmation.reservationId': 'Reservation ID',
    'booking.confirmation.paymentMethod': 'Payment Method',
    'booking.confirmation.viewAccount': 'View in My Account',

    // Admin Panel
    'admin.title': 'Admin Panel',
    'admin.heading': 'Administration',
    'admin.dashboard': 'Dashboard',
    'admin.reservations': 'Reservations',
    'admin.cruises': 'Cruises',
    'admin.blog': 'Blog',
    'admin.logout': 'Sign Out',
    'admin.common.all': 'All',
    'admin.common.save': 'Save',
    'admin.common.cancel': 'Cancel',
    'admin.common.edit': 'Edit',
    'admin.common.delete': 'Delete',
    'admin.common.view': 'View',
    'admin.common.actions': 'Actions',
    'admin.common.loading': 'Loading...',
    'admin.common.error': 'Error',
    'admin.dashboard.title': 'Control Panel',
    'admin.dashboard.confirmedRevenue': 'Confirmed Revenue',
    'admin.dashboard.pendingCount': 'Pending',
    'admin.dashboard.confirmedCount': 'Confirmed',
    'admin.dashboard.revenueByCruise': 'Revenue by Cruise',
    'admin.dashboard.confirmedReservations': 'Confirmed Reservations',
    'admin.dashboard.totalGuests': 'Total Guests',
    'admin.dashboard.revenue': 'Revenue',
    'admin.dashboard.noCruiseData': 'No cruise revenue data yet',
    'admin.dashboard.error': 'Error loading dashboard',
    'admin.reservations.title': 'Reservation Management',
    'admin.reservations.empty': 'No reservations found',
    'admin.reservations.filterStatus': 'Status',
    'admin.reservations.id': 'ID',
    'admin.reservations.cruise': 'Cruise',
    'admin.reservations.date': 'Date',
    'admin.reservations.tier': 'Tier',
    'admin.reservations.guests': 'Guests',
    'admin.reservations.total': 'Total',
    'admin.reservations.status': 'Status',
    'admin.reservations.approve': 'Approve',
    'admin.reservations.cancel': 'Cancel',
    'admin.reservations.suspend': 'Suspend',
    'admin.reservationDetail.title': 'Reservation Detail',
    'admin.reservationDetail.subtitle': 'Complete reservation information',
    'admin.reservationDetail.id': 'Reservation ID',
    'admin.reservationDetail.userId': 'User ID',
    'admin.reservationDetail.cruise': 'Cruise',
    'admin.reservationDetail.departureDate': 'Departure Date',
    'admin.reservationDetail.route': 'Route',
    'admin.reservationDetail.tier': 'Tier',
    'admin.reservationDetail.tierPrice': 'Tier Price',
    'admin.reservationDetail.guestCount': 'Guest Count',
    'admin.reservationDetail.totalAmount': 'Total Amount',
    'admin.reservationDetail.paymentMethod': 'Payment Method',
    'admin.reservationDetail.createdAt': 'Created At',
    'admin.reservationDetail.cruiseId': 'Cruise ID',
    'admin.reservationDetail.notes': 'Notes',
    'admin.reservationDetail.notesPlaceholder': 'Crew names, preferences...',
    'admin.reservationDetail.notesHelp': 'Save notes about the reservation (crew, preferences, etc.)',
    'admin.cruises.title': 'Cruise Management',
    'admin.cruises.empty': 'No cruises found',
    'admin.cruises.add': 'Add Cruise',
    'admin.cruises.edit': 'Edit Cruise',
    'admin.cruises.confirmDelete': 'Delete this cruise?',
    'admin.cruise.name': 'Name',
    'admin.cruise.departureDate': 'Departure Date',
    'admin.cruise.returnDate': 'Return Date',
    'admin.cruise.route': 'Route',
    'admin.cruise.boat': 'Boat',
    'admin.cruise.dives': 'Dives',
    'admin.cruise.basic': 'Basic',
    'admin.cruise.standard': 'Standard',
    'admin.cruise.premium': 'Premium',
    'admin.cruise.status': 'Status',
    'admin.cruise.active': 'Active',
    'admin.cruise.inactive': 'Inactive',
    'admin.cruise.namePlaceholder': 'e.g. Socorro Islands',
    'admin.cruise.routePlaceholder': 'e.g. Revillagigedo Archipelago',
    'admin.blog.title': 'Blog Management',
    'admin.blog.empty': 'No posts found',
    'admin.blog.add': 'Add Post',
    'admin.blog.edit': 'Edit Post',
    'admin.blog.confirmDelete': 'Delete this post?',
    'admin.blog.fifoLabel': 'Published posts:',
    'admin.blog.titleCol': 'Title',
    'admin.blog.status': 'Status',
    'admin.blog.createdAt': 'Created At',
    'admin.blog.published': 'Published',
    'admin.blog.draft': 'Draft',
    'admin.blog.formTitle': 'Title',
    'admin.blog.formTitlePlaceholder': 'Post title',
    'admin.blog.formContent': 'Content',
    'admin.blog.formContentPlaceholder': 'Post content...',
    'admin.blog.formImageUrl': 'Image URL',
    'admin.blog.formStatus': 'Status',
    'admin.blog.fifoWarning': 'When publishing, if there are already 5 posts, the oldest will be automatically deleted.',

    // Calendar
    'calendar.title': 'Expedition Calendar',
    'calendar.subtitle': 'Explore our upcoming departures and find your next adventure',
    'calendar.available': 'Expedition Available',
    'calendar.noDates': 'No expeditions scheduled at this time. Check back soon or contact us for upcoming dates.',
    'calendar.loading': 'Loading calendar...',
    'calendar.error': 'Could not load expeditions. Please try again.',
    'calendar.retry': 'Retry',
    'calendar.bookNow': 'Book Now',
    'calendar.dives': 'dives',
    'calendar.from': 'From',
    'calendar.departs': 'Departs',
    'calendar.returns': 'Returns',
    'calendar.days': 'days',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.ourBoat': 'Nuestro Barco',
    'nav.destinations': 'Destinos',
    'nav.faqs': 'Preguntas Frecuentes',
    'nav.aboutUs': 'Sobre Nosotros',
    'nav.collaborations': 'Colaboraciones',
    'nav.calendar': 'Expediciones',
    'nav.blogs': 'Blog',
    'nav.admin': 'Admin',
    'nav.contact': 'Contacto',
    'nav.bookNow': 'Reservar',
    'nav.menu': 'Menú',
    'nav.signOut': 'Cerrar sesión',

    // Hero
    'hero.title': 'Quetzal',
    'hero.subtitle': 'LA MEJOR AVENTURA DE BUCEO EN EL OCÉANO TE ESPERA',
    'hero.button': 'Ver Calendario',

    // Experience Section
    'experience.title': 'Lo Que Te Espera A Bordo',
    'experience.subtitle': 'Cada momento a bordo del Quetzal es una invitación a lo extraordinario.',
    'experience.cta': 'Descubre más',
    'experience.item1': 'Sumérgete en lo Desconocido',
    'experience.item1Desc': 'Desciende a un mundo que pocos llegan a ver. Cada inmersión en Revillagigedo revela algo nuevo — desde montañas submarinas volcánicas hasta un azul infinito. Nuestros guías expertos te llevan por los sitios más espectaculares del archipiélago.',
    'experience.item2': 'Nada con Gigantes',
    'experience.item2Desc': 'Comparte el agua con majestuosas mantas gigantes, delfines curiosos y ballenas migratorias. Estos encuentros no son solo avistamientos — son momentos que se quedan contigo para siempre.',
    'experience.item3': 'Explora Costas Vírgenes',
    'experience.item3Desc': 'Entre inmersiones, descubre playas remotas, calas escondidas y paisajes volcánicos. Las islas de Revillagigedo son tan dramáticas sobre el agua como debajo de ella.',
    'experience.item4': 'Presencia el Espectáculo',
    'experience.item4Desc': 'Cardúmenes de tiburones martillo, puntas blancas de arrecife, tiburones sedosos — el archipiélago alberga algunas de las congregaciones marinas más impresionantes de la Tierra. Cada inmersión es un asiento en primera fila a la naturaleza en su estado más salvaje.',

    // Destination Section
    'destination.days': '7 DÍAS DE EXPLORACIÓN',
    'destination.title': 'MAR DE CORTÉS',
    'destination.year': '2026 DESDE',
    'destination.price': '$2,350 USD POR PERSONA',
    'destination.cta': 'Consulta con Nuestro Experto',

    // Boat Gallery
    'boat.gallery.title': 'Nuestro Bote',
    'boat.gallery.subtitle': 'Sube a bordo del Quetzal — una embarcación clásica diseñada para la comodidad, la aventura y momentos inolvidables en el mar.',
    'boat.gallery.staterooms': 'Habitaciones',
    'boat.gallery.interior': 'Interior',

    // Marine Life Section
    'marine.title': 'Esto Es Lo Que Verás Con Nosotros',
    'marine.description': 'Únete a la aventura a bordo de Quetzal y presencia la impresionante vida marina—exactamente lo que nuestros huéspedes ven en esta inolvidable experiencia submarina.',
    'marine.cta': 'Ver Próximos Viajes',

    // Destinations Grid
    'destinations.title': 'Nuestros Destinos',
    'destinations.subtitle': 'Donde Comienza La Aventura',
    'destinations.socorro.title': 'SOCORRO',
    'destinations.socorro.description': 'Nacido de volcanes, Socorro es una de las cuatro islas que conforman el Archipiélago de Revillagigedo. Se encuentran en una ubicación geográfica única que atrae a una vida marina increíble.',
    'destinations.magbay.title': 'BAHÍA MAGDALENA + SOCORRO',
    'destinations.magbay.description': 'Embárcate en una aventura de 14 días desde Los Cabos hasta Bahía Magdalena y Socorro, buceando con ballenas, tiburones y mantas diariamente.',
    'destinations.cortez.title': 'MAR DE CORTÉS',
    'destinations.cortez.description': '¡Visita uno de los lugares más hermosos del planeta, con días llenos de agua salada y sol, montañas, vida silvestre, cultura e historia!',
    'destinations.explore': 'Explorar Destino',

    // Upcoming Trips
    'trips.title': 'Próximo Destino',
    'trips.subtitle': 'Guiados por Experiencia Perfeccionados por Pasión',
    'trips.trip1.title': 'Bahía Magdalena e Islas Socorro',
    'trips.trip1.dates': '16 OCT 2025 - 30 OCT 2025',
    'trips.trip1.price': 'desde $5,199 USD por persona',
    'trips.trip2.title': 'Islas Socorro (Revillagigedo)',
    'trips.trip2.dates': '06 ENE 2026 - 14 ENE 2026',
    'trips.trip2.price': 'desde $3,500 USD por persona',
    'trips.trip3.title': 'Viaje al Mar de Cortés',
    'trips.trip3.dates': '09 JUL 2026 - 16 JUL 2026',
    'trips.trip3.price': 'desde $2,350 USD por persona',
    'trips.details': 'Detalles del Viaje y Precios',

    // Testimonials
    'testimonials.title': 'Lo Que Dicen Nuestros Huéspedes',
    'testimonials.subtitle': 'No solo confíes en nuestra palabra—escucha a los buzos que han experimentado la aventura de su vida',

    // Gallery
    'gallery.title': 'Momentos Capturados',
    'gallery.subtitle': 'Experimenta la belleza bajo las olas',
    'gallery.promise': 'Esto es lo que te espera',
    'gallery.scrollHint': 'Desliza para descubrir',

    // Contact Form
    'contact.title': 'Planifica Tu Viaje Con Nosotros',
    'contact.description': 'Usa el formulario para contactar a nuestro equipo — estamos aquí para ayudarte a reservar y preparar tu experiencia Quetzal.',
    'contact.email': 'Correo electrónico:',
    'contact.name': 'Nombre',
    'contact.emailField': 'Correo Electrónico',
    'contact.destinations': 'Destinos',
    'contact.message': 'Mensaje',
    'contact.submit': 'Enviar',
    'contact.required': 'Los campos marcados con * son obligatorios',
    'contact.success': '¡Gracias! Nos pondremos en contacto pronto.',
    'contact.error': 'Algo salió mal. Por favor intenta de nuevo.',

    // Footer
    'footer.brand': 'Experimenta la mejor aventura de buceo en barco en el Océano Pacífico. Expediciones a los destinos más extraordinarios de México.',
    'footer.destinations': 'Destinos',
    'footer.socorro': 'Islas Socorro',
    'footer.cortez': 'Mar de Cortés',
    'footer.magBay': 'Bahía Magdalena',
    'footer.company': 'Compañía',
    'footer.contactForm': 'Formulario de Contacto',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',
    'footer.cancellation': 'Política de Cancelación',
    'footer.divingRisks': 'Riesgos de Buceo',

    // Our Boat Page
    'boat.hero': 'Conoce el Quetzal',
    'boat.subtitle': 'Una embarcación clásica de lujo diseñada para la exploración, la comodidad y los momentos inolvidables en alta mar.',
    'boat.specs.title': 'Especificaciones del Barco',
    'boat.specs.length': 'Eslora',
    'boat.specs.lengthVal': '120 ft (36.5 m)',
    'boat.specs.beam': 'Manga',
    'boat.specs.beamVal': '24 ft (7.3 m)',
    'boat.specs.guests': 'Huéspedes',
    'boat.specs.guestsVal': 'Hasta 20',
    'boat.specs.cabins': 'Cabinas',
    'boat.specs.cabinsVal': '10 Privadas',
    'boat.specs.speed': 'Velocidad de Crucero',
    'boat.specs.speedVal': '10 nudos',
    'boat.specs.compressor': 'Compresores',
    'boat.specs.compressorVal': '2x Bauer',
    'boat.comfort.title': 'Comodidad a Bordo',
    'boat.comfort.subtitle': 'Cada detalle está diseñado para que te enfoques en lo importante — la aventura.',
    'boat.comfort.dining': 'Cena Gourmet',
    'boat.comfort.diningDesc': 'Comidas recién preparadas con mariscos locales y cocina internacional, acompañadas de vinos finos y bebidas frías.',
    'boat.comfort.sunDeck': 'Solárium y Terraza',
    'boat.comfort.sunDeckDesc': 'Una cubierta superior espaciosa con tumbonas y zonas con sombra, perfecta para cócteles al atardecer entre inmersiones.',
    'boat.comfort.cabin': 'Cabinas Privadas',
    'boat.comfort.cabinDesc': 'Cabinas cómodas con aire acondicionado, baños privados y amplio espacio de almacenamiento para tu equipo.',
    'boat.comfort.dive': 'Plataforma de Buceo',
    'boat.comfort.diveDesc': 'Un área de buceo diseñada con estaciones individuales de equipo, tanques de enjuague para cámaras y duchas de agua caliente.',

    // Destination Pages
    'dest.hero': 'Explora Nuestros',
    'dest.heroHighlight': 'Destinos',
    'dest.backAll': 'Ver Todos los Destinos',
    'dest.fromPrice': 'Desde',
    'dest.perPerson': 'por persona',
    'dest.duration': 'Duración',
    'dest.nextDeparture': 'Próxima Salida',
    'dest.bookNow': 'Reservar Este Viaje',
    'dest.calendar': 'Calendario de Fauna',

    // Socorro
    'socorro.title': 'Islas Socorro',
    'socorro.subtitle': 'Las Galápagos de México',
    'socorro.description1': 'El Archipiélago de Revillagigedo, conocido como las Islas Socorro, es Patrimonio de la Humanidad por la UNESCO, ubicado a 250 millas al sur de Cabo San Lucas. Estas islas volcánicas emergen del océano profundo, creando un ecosistema único que atrae a las especies marinas más grandes del planeta.',
    'socorro.description2': 'Desde mantas oceánicas gigantes con envergaduras de más de 6 metros hasta bancos de tiburones martillo, delfines nariz de botella y encuentros estacionales con ballenas jorobadas — Socorro ofrece buceo de clase mundial que rivaliza con los mejores del planeta.',
    'socorro.highlights': 'Lo Que Verás',
    'socorro.h1': 'Mantas Oceánicas Gigantes',
    'socorro.h1d': 'Observa mantas con envergaduras de más de 6 metros planear graciosamente en aguas cristalinas, a menudo acercándose a los buzos con gentil curiosidad.',
    'socorro.h2': 'Bancos de Tiburones Martillo',
    'socorro.h2d': 'Buzca entre cientos de tiburones martillo reunidos en estaciones de limpieza, un espectáculo impresionante único en estas aguas.',
    'socorro.h3': 'Ballenas Jorobadas',
    'socorro.h3d': 'Entre enero y abril, las ballenas jorobadas visitan estas aguas. Escucha sus cantos submarinos y presenciar espectaculares saltos.',
    'socorro.h4': 'Delfines y Pelágicos Grandes',
    'socorro.h4d': 'Delfines nariz de botella juguetones se acercan frecuentemente a los buzos, mientras atunes, wahoos y otros pelágicos grandes patrullan el azul.',
    'socorro.h5': 'Tiburones Tigre y Sedosos',
    'socorro.h5d': 'Depredadores oceánicos como tiburones tigre, sedosos y puntas blancas oceánicos patrullan las aguas azules profundas alrededor de estas islas volcánicas.',
    'socorro.h6': 'Tiburones Ballena y Falsas Orcas',
    'socorro.h6d': 'Los tiburones ballena visitan en noviembre, diciembre y mayo. Mayo también trae bolas de carnada gigantes y manadas de falsas orcas.',
    'socorro.diveSites.title': 'Sitios de Buceo',
    'socorro.diveSites.sanBenedicto.boiler.name': 'El Boiler',
    'socorro.diveSites.sanBenedicto.boiler.description': 'Un monte marino sumergido que se eleva desde el fondo del océano hasta unos 50m — una reconocida estación de limpieza de mantas donde los gigantes se reúnen.',
    'socorro.diveSites.sanBenedicto.boiler.fauna': 'Mantas oceánicas gigantes (hasta 6m+), delfines nariz de botella, amberjack, jureles, atún aleta amarilla',
    'socorro.diveSites.sanBenedicto.canyon.name': 'El Cañón',
    'socorro.diveSites.sanBenedicto.canyon.description': 'Mantas enormes deambulan por este sitio — envergaduras de 4m+ dando vueltas sobre los buzos. Los cantos de ballenas jorobadas se escuchan bajo el agua.',
    'socorro.diveSites.sanBenedicto.canyon.fauna': 'Mantas gigantes, mantas negras, ballenas jorobadas (cantos), tiburones ballena',
    'socorro.diveSites.rocaPartida.rocaPartida.name': 'Roca Partida',
    'socorro.diveSites.rocaPartida.rocaPartida.description': 'Un enorme arrecife que se eleva en medio del océano abierto con paredes de 70-80m. Tan remoto que toma 6 horas en barco desde San Benedicto.',
    'socorro.diveSites.rocaPartida.rocaPartida.fauna': 'Bancos de tiburones martillo (cientos), tiburones punta plateada, jureles negros, tiburones tigre, tiburones ballena, tiburones Galápagos',
    'socorro.diveSites.socorroIsland.caboPearce.name': 'Cabo Pearce',
    'socorro.diveSites.socorroIsland.caboPearce.description': 'Un monte marino que se extiende hacia el mar abierto frente a la Isla Socorro. Múltiples encuentros con grandes criaturas en cada inmersión.',
    'socorro.diveSites.socorroIsland.caboPearce.fauna': 'Delfines nariz de botella, tiburones martillo, tiburones Galápagos, tiburones punta plateada, mantas gigantes (escenas de depredación), ballenas jorobadas',
    'socorro.calendar.jan': 'Ballenas jorobadas, mantas gigantes, tiburones martillo, delfines nariz de botella',
    'socorro.calendar.feb': 'Ballenas jorobadas (pico), mantas gigantes, tiburones martillo, delfines nariz de botella',
    'socorro.calendar.mar': 'Ballenas jorobadas (pico), mantas gigantes, tiburones martillo, delfines nariz de botella',
    'socorro.calendar.apr': 'Ballenas jorobadas, mantas gigantes, tiburones martillo, delfines nariz de botella',
    'socorro.calendar.may': 'Mantas gigantes, tiburones martillo, delfines, tiburones ballena, falsas orcas, bolas de carnada gigantes',
    'socorro.calendar.jun': 'Mantas gigantes, tiburones martillo, delfines nariz de botella',
    'socorro.calendar.jul': 'Mantas gigantes, tiburones martillo, delfines nariz de botella',
    'socorro.calendar.nov': 'Mantas gigantes, tiburones martillo, delfines nariz de botella, tiburones ballena',
    'socorro.calendar.dec': 'Mantas gigantes, tiburones martillo, delfines nariz de botella, tiburones ballena',
    'socorro.conservation.unesco': 'Patrimonio Mundial de la UNESCO',
    'socorro.conservation.protectedArea': 'Parque Nacional Archipiélago de Revillagigedo',
    'socorro.conservation.designation': 'Designado en 2016',
    'socorro.gallery.title': 'Galería',
    'socorro.gallery.images': '[{"src":"/images/panoramicas/Isla Socorro.webp","alt":"Acantilados volcánicos de la Isla Socorro emergiendo del Pacífico"},{"src":"/images/panoramicas/Manta el Boiler 1.webp","alt":"Manta oceánica gigante en la estación de limpieza de El Boiler"},{"src":"/images/panoramicas/Cabo Pearce .webp","alt":"Paisaje marino en el sitio de buceo Cabo Pearce"},{"src":"/images/panoramicas/Clariones.webp","alt":"La remota isla volcánica de Clarion"},{"src":"/images/panoramicas/Pargos Roca.webp","alt":"Cardumen de pargos en Roca Partida"},{"src":"/images/panoramicas/Delfin Kike.webp","alt":"Delfines nariz de botella jugando en la proa"}]',

    // Sea of Cortez
    'cortez.title': 'Mar de Cortés',
    'cortez.subtitle': 'El Acuario del Mundo',
    'cortez.description1': 'Jacques Cousteau llamó al Mar de Cortés "el acuario del mundo", y con razón. Este estrecho cuerpo de agua entre la península de Baja California y el México continental es uno de los ambientes marinos más biodiversos del planeta.',
    'cortez.description2': 'Más de 900 especies de peces, miles de invertebrados y un tercio de las especies de cetáceos del mundo habitan estas aguas. Desde colonias de lobos marinos hasta avistamiento de ballenas, desde nudibranquios coloridos hasta tiburones ballena — el Mar de Cortés ofrece una diversidad inigualable.',
    'cortez.highlights': 'Lo Que Verás',
    'cortez.h1': 'Colonias de Lobos Marinos',
    'cortez.h1d': 'Juega con curiosos lobos marinos en la Isla Espíritu Santo — les encanta girar, dar vueltas y soplar burbujas alrededor de los buzos.',
    'cortez.h2': 'Tiburones Ballena',
    'cortez.h2d': 'Nada junto al pez más grande del mundo en las aguas ricas en nutrientes de Bahía de La Paz, una experiencia verdaderamente humilde.',
    'cortez.h3': 'Vida Arrecifal Colorida',
    'cortez.h3d': 'Vibrantes nudibranquios, morenas, pulpos y más de 700 especies de peces de arrecife hacen de cada inmersión una búsqueda del tesoro.',
    'cortez.h4': 'Paisajes Impresionantes',
    'cortez.h4d': 'Dramáticos paisajes desérticos, caletas apartadas e islas montañosas crean un escenario impresionante sobre y bajo el agua.',
    'cortez.h5': 'Mantarrayas Mobula',
    'cortez.h5d': 'De julio a octubre, las mantarrayas mobula se reúnen por miles en Punta Lobo — saltando, girando y llenando el agua de superficie a fondo.',
    'cortez.h6': 'Vida Macro y Naufragios',
    'cortez.h6d': 'Bluespotted Jawfish, Signal blennies, jawfishes gigantes, nudibranquios — y el ferry Salvatierra de 80 metros rebosante de peces de arrecife de tamaño excepcional.',
    'cortez.diveSites.title': 'Sitios de Buceo',
    'cortez.diveSites.laPazBay.losIslotes.name': 'Los Islotes',
    'cortez.diveSites.laPazBay.losIslotes.description': 'Un islote rocoso hogar de una colonia de más de 400 lobos marinos de California. Las crías empiezan a jugar con los buzos en septiembre — mordisquean aletas y snorkels en la cueva del lado sur.',
    'cortez.diveSites.laPazBay.losIslotes.fauna': '400+ lobos marinos de California, Bluespotted Jawfish, cardúmenes de sardinas, mantarrayas mobula, barracudas mexicanas, gobios, nudibranquios',
    'cortez.diveSites.laPazBay.laPazBay.name': 'Bahía de La Paz',
    'cortez.diveSites.laPazBay.laPazBay.description': 'La bahía se ha convertido en un lugar confiable para nadar con tiburones ballena — el pez más grande del mundo — en sus zonas naturales de alimentación.',
    'cortez.diveSites.laPazBay.laPazBay.fauna': 'Tiburones ballena',
    'cortez.diveSites.laPazBay.swanneeReef.name': 'Arrecife Swannee',
    'cortez.diveSites.laPazBay.swanneeReef.description': 'Un arrecife aislado en un área de arena blanca — un paraíso de peces. Los Signal blennies salen de sus agujeros, emitiendo su aleta dorsal tres veces antes de retirarse.',
    'cortez.diveSites.laPazBay.swanneeReef.fauna': 'Goatfish mexicanos, Spottail grunt, Signal blennies, barracudas, skip jacks, lobos marinos (ocasionales)',
    'cortez.diveSites.laPazBay.salvatierra.name': 'Naufragio Salvatierra',
    'cortez.diveSites.laPazBay.salvatierra.description': 'Un ferry de 80 metros hundido a unos 20m de profundidad, casi completamente intacto. Se ha convertido en un próspero arrecife artificial.',
    'cortez.diveSites.laPazBay.salvatierra.fauna': 'Grunts y peces ángel de tamaño excepcional, peces de arrecife',
    'cortez.diveSites.laPazBay.elCorralito.name': 'El Corralito',
    'cortez.diveSites.laPazBay.elCorralito.description': 'Conocido por sus jawfishes singularmente gigantes — notablemente más grandes que en cualquier otro lugar del Mar de Cortés.',
    'cortez.diveSites.laPazBay.elCorralito.fauna': 'Jawfishes gigantes',
    'cortez.diveSites.northernIslands.elBajo.name': 'El Bajo',
    'cortez.diveSites.northernIslands.elBajo.description': 'Tres montes marinos con cimas a 18-22m. Derivas entre cientos de tiburones martillo serpenteando sus cabezas y cuerpos a tu alrededor.',
    'cortez.diveSites.northernIslands.elBajo.fauna': 'Tiburones martillo (cientos, adultos y juveniles), bonitos, skip jacks, marlines, tiburones ballena',
    'cortez.diveSites.northernIslands.whaleIsland.name': 'Isla Ballena',
    'cortez.diveSites.northernIslands.whaleIsland.description': 'Una isla escarpada con forma de ballena. Cuevas en el lado suroeste llevan al norte a través de pasajes llenos de abanicos de mar.',
    'cortez.diveSites.northernIslands.whaleIsland.fauna': 'Pez ángel de Cortés, abanicos de mar, peces de arrecife',
    'cortez.diveSites.northernIslands.sanFrancisquito.name': 'San Francisquito',
    'cortez.diveSites.northernIslands.sanFrancisquito.description': 'Un sitio de buceo solo accesible por liveaboard. Sin la competencia territorial de sitios más concurridos, los lobos marinos aquí son más tranquilos y relajados.',
    'cortez.diveSites.northernIslands.sanFrancisquito.fauna': 'Lobos marinos de California (tranquilos, relajados), peces de arrecife',
    'cortez.diveSites.eastCape.lasAnimas.name': 'Las Ánimas',
    'cortez.diveSites.eastCape.lasAnimas.description': 'Solo accesible por liveaboard. Rayas diamante gigantes se deslizan entre coloridos abanicos de mar mientras big eye trevallies giran en remolinos.',
    'cortez.diveSites.eastCape.lasAnimas.fauna': 'Longnose hawkfish, rayas diamante gigantes, abanicos de mar, big eye trevallies, tiburones martillo, tortugas marinas',
    'cortez.diveSites.eastCape.caboPulmo.name': 'Cabo Pulmo / Gordo Banks',
    'cortez.diveSites.eastCape.caboPulmo.description': 'A ocho millas de la costa, profundidades de hasta 40m con corrientes poderosas — solo para buzos avanzados. Uno de los mejores sitios de buceo de la región.',
    'cortez.diveSites.eastCape.caboPulmo.fauna': 'Grandes cardúmenes de jureles, tiburones toro, peces de arrecife',
    'cortez.calendar.aug': 'Tiburones ballena, tiburones martillo, mantarrayas mobula (inicio de temporada), lobos marinos',
    'cortez.calendar.sep': 'Tiburones ballena, tiburones martillo, mantarrayas mobula (pico — miles), lobos marinos (crías empiezan a jugar con buzos)',
    'cortez.calendar.oct': 'Tiburones ballena, tiburones martillo, mantarrayas mobula (pico), lobos marinos',
    'cortez.calendar.nov': 'Lobos marinos (alta actividad), tiburones martillo, tiburones ballena (disminuyendo), mantarrayas mobula',
    'cortez.conservation.unesco': 'Patrimonio Mundial de la UNESCO',
    'cortez.conservation.protectedArea': 'Islas y Áreas Protegidas del Golfo de California',
    'cortez.conservation.designation': 'Designado en 2005',
    'cortez.gallery.title': 'Galería',
    'cortez.gallery.images': '[{"src":"/images/panoramicas/PuntaTosca.webp","alt":"Escarpada costa de Punta Tosca, Baja California Sur"},{"src":"/images/panoramicas/loreto-magdalena-bay.webp","alt":"Aguas prístinas de Loreto y Bahía Magdalena"},{"src":"/images/panoramicas/ROca Partida .webp","alt":"El icónico pináculo de Roca Partida en mar abierto"},{"src":"/images/panoramicas/Quetzal San Bene.webp","alt":"El Quetzal anclado frente a la Isla San Benedicto"},{"src":"/images/panoramicas/Manta Clariones.webp","alt":"Manta raya deslizándose en aguas cristalinas"}]',

    // Magdalena Bay
    'magbay.title': 'Bahía Magdalena',
    'magbay.subtitle': 'Donde las Ballenas Encuentran el Desierto',
    'magbay.description1': 'Bahía Magdalena es uno de los mejores secretos de Baja California. Esta vasta laguna protegida en la costa del Pacífico es famosa mundialmente como guardería de ballenas grises, que viajan más de 16,000 kilómetros para parir en sus aguas cálidas.',
    'magbay.description2': 'Combinada con un viaje a Socorro, esta expedición ofrece la rara oportunidad de experimentar tanto la intimidad de los encuentros cercanos con ballenas en la bahía como la adrenalina del buceo de animales grandes en el archipiélago — dos mundos en un viaje inolvidable.',
    'magbay.highlights': 'Lo Que Verás',
    'magbay.h1': 'Encuentros con Ballenas Grises',
    'magbay.h1d': 'Llega a estar a un brazo de distancia de gentiles ballenas grises y sus crías — una de las experiencias de vida silvestre más profundas que existen.',
    'magbay.h2': 'Canales de Manglar',
    'magbay.h2d': 'Haga kayak por prístinos canales de manglar llenos de aves, rayas y peces tropicales en aguas cristalinas.',
    'magbay.h3': 'Vida Silvestre del Desierto',
    'magbay.h3d': 'Observa coyotes, águilas pescadoras y zorros del desierto a lo largo de las dunas y playas remotas de Isla Magdalena.',
    'magbay.h4': 'Buceo en Socorro',
    'magbay.h4d': 'La segunda mitad trae mantas, tiburones y delfines en el Archipiélago de Revillagigedo — lo mejor de ambos mundos.',
    'magbay.h5': 'Corrida de Sardinas de México',
    'magbay.h5d': 'De octubre a diciembre, el lado Pacífico de Baja explota de vida durante la corrida anual de sardinas — atrayendo marlines rayados, aves marinas y cetáceos en espectaculares frenesíes alimenticios.',
    'magbay.h6': 'Expedición de 14 Días',
    'magbay.h6d': 'Dos mundos en un viaje inolvidable: la intimidad de los encuentros cercanos con ballenas en la bahía, seguido del buceo de animales grandes con mantas, tiburones y delfines en el Archipiélago de Revillagigedo.',
    'magbay.calendar.jan': 'Ballenas grises (pico), madres y crías en la laguna',
    'magbay.calendar.feb': 'Ballenas grises (pico), encuentros cercanos íntimos',
    'magbay.calendar.mar': 'Ballenas grises (pico), madres y crías',
    'magbay.calendar.apr': 'Ballenas grises (últimas semanas)',
    'magbay.calendar.oct': 'Comienza la corrida de sardinas — marlines rayados, aves marinas, cetáceos',
    'magbay.calendar.nov': 'Corrida de sardinas (pico), explosión de vida en el Pacífico',
    'magbay.calendar.dec': 'Corrida de sardinas, bolas de carnada masivas',
    'magbay.conservation.unesco': 'Santuario Ballenero de la UNESCO',
    'magbay.conservation.protectedArea': 'Laguna Protegida Bahía Magdalena',
    'magbay.conservation.designation': 'Parte del Patrimonio Mundial de la UNESCO',
    'magbay.gallery.title': 'Galería',
    'magbay.gallery.images': '[{"src":"/images/panoramicas/loreto-magdalena-bay.webp","alt":"La laguna protegida de Bahía Magdalena al atardecer"},{"src":"/images/panoramicas/Puntas blancas 1.webp","alt":"Tiburones punta blanca descansando en el fondo arenoso"},{"src":"/images/panoramicas/Puntas blancas 4.webp","alt":"Curiosos tiburones punta blanca patrullando el arrecife"},{"src":"/images/panoramicas/Puntas blancas Balcón.webp","alt":"Vista panorámica desde el sitio de buceo El Balcón"}]',

    // FAQ Page
    'faq.title': 'Preguntas Frecuentes',
    'faq.subtitle': 'Todo lo que necesitas saber antes de tu expedición.',
    'faq.booking.title': 'Reservaciones y Pagos',
    'faq.q1': '¿Cómo reservo un viaje?',
    'faq.a1': 'Puedes reservar directamente a través de nuestro formulario de contacto, enviarnos un correo electrónico o contactar a nuestros expertos en viajes que te ayudarán a encontrar la expedición perfecta.',
    'faq.q2': '¿Cuál es la política de cancelación?',
    'faq.a2': 'Cancelaciones hechas más de 120 días antes de la salida reciben un reembolso completo menos una tarifa de procesamiento de $200 USD. Entre 60–120 días, 50% de reembolso. Menos de 60 días, sin reembolso. Recomendamos encarecidamente un seguro de viaje.',
    'faq.q3': '¿Ofrecen descuentos grupales?',
    'faq.a3': '¡Sí! Grupos de 6 o más reciben un 10% de descuento. Para grupos más grandes o consultas de fletamento, contáctanos directamente para precios personalizados.',
    'faq.preparation.title': 'Preparación y Equipaje',
    'faq.q4': '¿Qué nivel de certificación necesito?',
    'faq.a4': 'La mayoría de las inmersiones requieren certificación Open Water con al menos 25 inmersiones registradas. Para Socorro, recomendamos Advanced Open Water debido a las corrientes y profundidad. Los no buzos también son bienvenidos para snorkel y actividades en la superficie.',
    'faq.q5': '¿Qué debo empacar?',
    'faq.a5': 'Proporcionamos una lista detallada de empaque al reservar. Lo esencial incluye: protector solar ecológico, medicación para mareos, traje de neopreno de 3mm (5mm para invierno), computadora de buceo y una cámara si tienes.',
    'faq.q6': '¿Necesito seguro de viaje?',
    'faq.a6': 'Recomendamos encarecidamente un seguro de viaje integral que incluya cobertura de evacuación de buceo (membresía DAN). Esto te protege contra cancelaciones, emergencias médicas y escenarios de evacuación.',
    'faq.onboard.title': 'Experiencia a Bordo',
    'faq.q7': '¿Cómo son las cabinas?',
    'faq.a7': 'Todas las cabinas son privadas con aire acondicionado, baños privados, enchufes de 110V y espacio de almacenamiento. Las categorías van de Estándar a Suite Master. Toda la ropa de cama y toallas están incluidas.',
    'faq.q8': '¿Cuántas inmersiones por día?',
    'faq.a8': 'Típicamente 3-4 inmersiones por día incluyendo una inmersión nocturna cuando las condiciones lo permiten. Los horarios de buceo son flexibles y dependen del clima.',
    'faq.q9': '¿Y las restricciones alimentarias?',
    'faq.a9': 'Nuestro chef puede acomodar la mayoría de las necesidades dietéticas incluyendo vegetariano, vegano, sin gluten y kosher. Por favor infórmanos al menos 2 semanas antes de la salida.',

    // About Page
    'about.title': 'Tu Historia con el Océano Empieza Acá',
    'about.subtitle': 'Donde la aventura se encuentra con la calma — y vos sos el protagonista.',
    'about.story': 'Tu Viaje Empieza',
    'about.storyText1': 'Te despertás con el sonido del mar — el balanceo suave del barco, la sal en el aire, y la primera luz asomando en el horizonte.',
    'about.storyText2': 'Esto no es un tour. Es tu expedición. Desde el momento en que subís a bordo, cada ritmo del día gira alrededor de tu experiencia — tus inmersiones, tu ritmo, tu conexión con el océano.',
    'about.storyText3': 'Vas a explorar ecosistemas marinos remotos que pocas personas llegan a ver. Mantas gigantes que planean a tu lado en Socorro. Tiburones ballena en el Mar de Cortés. Arrecifes llenos de vida donde tu único público es el mar mismo.',
    'about.storyText4': 'Con grupos pequeños y una tripulación que ya sabe tu nombre al desayuno, nunca te vas a sentir como un número de pasajero. Tu comodidad, tu curiosidad y tu asombro son lo primero.',
    'about.storyText5': 'Comida fresca preparada para tu gusto, cabinas privadas pensadas para tu descanso, y cubiertas hechas para tus historias al atardecer. Cada detalle existe para que te concentres en lo que importa: la inmersión, el momento, el recuerdo.',
    'about.storyText6': 'Este es tu océano. Tu aventura. Tu historia — y empieza acá.',
    'about.values': 'Lo Que Vas a Vivir',
    'about.v1': 'Respeto por el Océano',
    'about.v1d': 'Vas a experimentar el océano no como un telón de fondo, sino como un mundo vivo. Cada inmersión está guiada por un profundo respeto por los ecosistemas marinos — para que te conectes con la naturaleza de forma responsable y significativa.',
    'about.v2': 'Exploración Auténtica',
    'about.v2d': 'Tu viaje no es un itinerario prefabricado. Vas a descubrir lugares salvajes en sus propios términos, guiado por quienes conocen cada corriente y cada cala — y quieren que sientas la emoción de la exploración real.',
    'about.v3': 'Conexión Personal',
    'about.v3d': 'Desde que subís a bordo, sos parte de la familia. Vas a compartir comidas, historias y atardeceres con una tripulación y compañeros que comparten tu pasión. No es solo servicio — es conexión humana genuina.',
    'about.v5': 'Hecho a Tu Medida',
    'about.v5d': 'Grupos chicos significan que tu experiencia se adapta a vos — no al revés. Horarios de buceo flexibles, atención personalizada y rincones tranquilos para cuando solo querés mirar el mar.',
    'about.cta': '¿Listo para Escribir Tu Propia Historia en el Océano?',
    'about.ctaButton': 'Empezá Tu Aventura',
    'about.socialProof': '+500 buzos han vivido esta experiencia',

    // Collaborations Page
    'collab.title': 'Nuestras Colaboraciones',
    'collab.subtitle': 'Trabajando juntos por un océano más sano.',
    'collab.intro': 'Creemos en el poder de la colaboración. Nuestras alianzas abarcan investigación marina, conservación y desarrollo comunitario — asegurando que cada expedición devuelva algo al océano y a las personas que dependen de él.',
    'collab.p1.name': 'Sylvia Earle Alliance',
    'collab.p1.desc': 'Apoyando Hope Spots de Mission Blue en el Archipiélago de Revillagigedo y el Mar de Cortés, contribuyendo datos a esfuerzos globales de conservación marina.',
    'collab.p2.name': 'Conservación PADI',
    'collab.p2.desc': 'Socio oficial de PADI AWARE. Realizamos encuestas de salud de arrecifes, limpiezas de desechos y ayudamos a certificar nuevos buzos en prácticas de conservación.',
    'collab.p3.name': 'Cooperativas Pesqueras Locales',
    'collab.p3.desc': 'Obtenemos nuestros mariscos de cooperativas locales sostenibles y proporcionamos oportunidades de ingresos alternativos a través de capacitación en ecoturismo.',
    'collab.p4.name': 'Investigación CICIMAR',
    'collab.p4.desc': 'Colaborando con el Centro de Investigación Científica y de Educación Superior de México para monitorear poblaciones de ballenas y la salud del océano.',
    'collab.cta': '¿Interesado en colaborar con nosotros?',
    'collab.ctaButton': 'Contáctanos',

    // Testimonials Page
    'testimonials.pageTitle': 'Testimonios de Huéspedes',
    'testimonials.pageSubtitle': 'Historias reales de aventureros reales.',
    'testimonials.all': 'Todos',
    'testimonials.socorro': 'Socorro',
    'testimonials.cortez': 'Mar de Cortés',
    'testimonials.magBay': 'Bahía Magdalena',

    // Blog Page
    'blog.title': 'El Diario Quetzal',
    'blog.subtitle': 'Historias, guías e insights del Pacífico Mexicano.',
    'blog.readMore': 'Leer Más',
    'blog.comingSoon': 'Próximamente',
    'blog.comingSoonDesc': 'Estamos preparando increíbles historias sobre nuestras expediciones, encuentros con vida marina y guías de viaje. ¡Mantente atento!',
    'blog.category': 'Categoría',
    'blog.catAll': 'Todas',
    'blog.catExpeditions': 'Expediciones',
    'blog.catMarine': 'Vida Marina',
    'blog.catGuides': 'Guías de Viaje',
    'blog.catConservation': 'Conservación',
    'blog.back': 'Volver al Blog',
    'blog.empty': 'Sin Publicaciones Aún',
    'blog.emptyDesc': 'Vuelve pronto para leer historias y actualizaciones de nuestras expediciones.',

    // Contact Page
    'contact.pageTitle': 'Contáctanos',
    'contact.pageSubtitle': '¿Listo para emprender la aventura de tu vida? Estamos aquí para ayudarte.',
    'contact.phone': 'Teléfono',
    'contact.phoneVal': '+52 624 123 4567',
    'contact.hours': 'Horario',
    'contact.hoursVal': 'Lun–Sáb, 9am–6pm MT',
    'contact.location': 'Ubicación',
    'contact.locationVal': 'Cabo San Lucas, BCS, México',
    'contact.social': 'Síguenos',

    // Shared
    'shared.backHome': 'Volver al Inicio',

    // Nav dropdown
    'nav.socorro': 'Islas Socorro',
    'nav.cortez': 'Mar de Cortés',
    'nav.magbay': 'Bahía Magdalena',

    // Legal
    'privacy.title': 'Política de Privacidad',
    'privacy.content': 'Estamos comprometidos con la protección de tu privacidad. Esta política describe cómo recopilamos, usamos y protegemos tu información personal al utilizar nuestro sitio web y reservar nuestros servicios. Para la política completa, contáctanos directamente.',
    'terms.title': 'Términos de Servicio',
    'terms.content': 'Al utilizar nuestro sitio web y reservar nuestros servicios, aceptas estos términos. Todas las reservaciones están sujetas a nuestra política de cancelación. Para los términos completos, contáctanos directamente.',

    // Booking Page
    'booking.title': 'Reserva Tu Expedición',
    'booking.steps.login': 'Acceso',
    'booking.steps.selectCruise': 'Seleccionar Crucero',
    'booking.steps.payment': 'Pago',
    'booking.flow.back': 'Atrás',
    'booking.flow.next': 'Siguiente',
    'booking.login.title': 'Accede a Tu Cuenta',
    'booking.login.email': 'Correo Electrónico',
    'booking.login.password': 'Contraseña',
    'booking.login.submit': 'Acceder',
    'booking.login.error': 'Correo electrónico o contraseña inválidos',
    'booking.login.invalid': 'Por favor ingresa una dirección de correo válida',
    'booking.register.title': 'Crea Tu Cuenta',
    'booking.register.name': 'Nombre Completo',
    'booking.register.email': 'Correo Electrónico',
    'booking.register.password': 'Contraseña',
    'booking.register.confirmPassword': 'Confirmar Contraseña',
    'booking.register.submit': 'Crear Cuenta',
    'booking.register.passwordMismatch': 'Las contraseñas no coinciden',
    'booking.register.invalid': 'Completa todos los campos',
    'booking.register.loginTab': 'Iniciar Sesión',
    'booking.register.registerTab': 'Registrarse',
    'booking.cruise.title': 'Selecciona Tu Crucero',
    'booking.cruise.select': 'Seleccionar',
    'booking.cruise.signIn': 'Inicia sesión',
    'booking.cruise.selected': 'Seleccionado',
    'booking.cruise.departure': 'Salida',
    'booking.cruise.route': 'Ruta',
    'booking.cruise.pricePerPerson': 'por persona',
    'booking.cruise.boat': 'Barco',
    'booking.cruise.tripDetails': 'Detalles del viaje',
    'booking.cruise.dives': 'días de inmersión',
    'booking.cruise.embarkation': 'Embarque',
    'booking.guest.title': 'Número de Huéspedes',
    'booking.guest.label': 'Huéspedes',
    'booking.guest.capacity': 'Capacidad: 18 máx',
    'booking.guest.increment': 'Agregar huésped',
    'booking.guest.decrement': 'Quitar huésped',
    'booking.guest.minReached': 'Se requiere mínimo 1 huésped',
    'booking.guest.maxReached': 'Máximo 18 huéspedes permitidos',
    'booking.payment.title': 'Completa Tu Reserva',
    'booking.payment.summary': 'Resumen de Reserva',
    'booking.payment.cruise': 'Crucero',
    'booking.payment.guests': 'Huéspedes',
    'booking.payment.total': 'Total',
    'booking.payment.payWithCard': 'Pagar con Tarjeta de Crédito',
    'booking.payment.payWithPaypal': 'Pagar con PayPal',
    'booking.payment.payWithBank': 'Pagar con Transferencia Bancaria',
    'booking.payment.confirming': 'Procesando...',
    'booking.payment.success': '¡Reserva confirmada! Nos pondremos en contacto contigo pronto.',
    'booking.confirmation.title': 'Reserva Confirmada',
    'booking.confirmation.message': 'Gracias por tu reserva. Nuestro equipo se pondrá en contacto contigo con los siguientes pasos.',
    'booking.confirmation.backHome': 'Volver al Inicio',

    // Booking Info Cards
    'booking.info.types': 'Tipos de Reserva',
    'booking.info.individual': 'Pase Individual',
    'booking.info.individualDesc': 'Reserva tu lugar en nuestras expediciones compartidas. Elige entre tres niveles de confort: Basic ($2,500), Standard ($3,000) o Premium ($3,500). Hasta 18 pasajeros por viaje.',
    'booking.info.half': 'Medio Charter',
    'booking.info.halfDesc': 'Reserva en grupo y ahorra. Por cada 8 espacios pagados, recibe 1 cortesía. Ideal para clubes de buceo, familias y grupos de amigos.',
    'booking.info.full': 'Full Charter',
    'booking.info.fullDesc': 'Tu expedición, a tu manera. Charter privado para tu grupo exclusivo con itinerario totalmente personalizado. Contáctanos para una cotización.',
    'booking.info.how': 'Cómo Funciona',
    'booking.info.choose': 'Elige tu Expedición',
    'booking.info.chooseDesc': 'Explora nuestros itinerarios a Islas Socorro, Mar de Cortés y Bahía Magdalena. Cada viaje ofrece encuentros marinos únicos.',
    'booking.info.signin': 'Inicia Sesión o Regístrate',
    'booking.info.signinDesc': 'Crea tu cuenta o inicia sesión para continuar. Tu información se guarda para una reserva más rápida la próxima vez.',
    'booking.info.guests': 'Selecciona tus Huéspedes',
    'booking.info.guestsDesc': 'Dinos cuántos aventureros te acompañarán. Viajero solitario, pareja o grupo — tenemos espacio para todos.',
    'booking.info.confirm': 'Confirma y Paga',
    'booking.info.confirmDesc': 'Revisa tu selección, completa el pago y recibe tu confirmación de reserva al instante por correo electrónico.',

    // Tier Pricing Keys
    'booking.tier.basic': 'Básico',
    'booking.tier.standard': 'Estándar',
    'booking.tier.premium': 'Premium',
    'booking.tier.selectHint': 'Selecciona un nivel de precio para continuar',
    'booking.tier.selected': 'Nivel seleccionado',
    'booking.payment.freeSpaces': 'Espacios gratuitos',
    'booking.payment.paidSpaces': 'Espacios pagados',
    'booking.payment.tierPrice': 'por persona (nivel)',
    'booking.fullCharter.label': 'Charter Privado',
    'booking.fullCharter.description': '¿Quieres toda la embarcación para ti? Contáctanos para un itinerario y precio personalizado.',
    'booking.fullCharter.cta': 'Contáctanos',
    'booking.confirmation.tier': 'Nivel de Precio',
    'booking.confirmation.freeSpaces': 'Espacios Gratis (Half Charter)',

    // Account Page
    'account.title': 'Mi Cuenta',
    'account.welcome': 'Bienvenido, {name}',
    'account.profile': 'Perfil',
    'account.reservations': 'Historial de Reservas',
    'account.save': 'Guardar',
    'account.edit': 'Editar',
    'account.name': 'Nombre',
    'account.email': 'Correo Electrónico',
    'account.phone': 'Teléfono',
    'account.noReservations': 'Sin reservas aún',
    'account.saveSuccess': 'Perfil actualizado correctamente',
    'account.status.pending': 'Pendiente',
    'account.status.confirmed': 'Confirmado',
    'account.status.completed': 'Completado',

    // Reservation Status
    'reservation.status.pending': 'Pendiente de Aprobación',
    'reservation.status.confirmed': 'Confirmada',
    'reservation.status.expired': 'Expirada',
    'reservation.status.cancelled': 'Cancelada',

    // Account Panel
    'account.reservations.title': 'Mis Reservaciones',
    'account.reservations.empty': 'Aún no tienes reservaciones. ¡Reserva una expedición!',
    'account.reservations.loading': 'Cargando reservaciones...',
    'account.reservations.error': 'Error al cargar las reservaciones',

    // Reservation Actions
    'reservation.actions.downloadPdf': 'Descargar PDF',
    'reservation.actions.emailReceipt': 'Enviar por Email',
    'reservation.actions.whatsappReceipt': 'Enviar por WhatsApp',
    'reservation.actions.holdExpires': 'El hold expira: {date}',
    'reservation.actions.expiredMessage': 'Esta reservación ha expirado y la fecha fue liberada.',

    // Payment Section
    'booking.payment.processing': 'Procesando...',
    'booking.payment.error': 'El pago falló. Intenta de nuevo.',
    'booking.payment.dateBlocked': 'Esta fecha ya no está disponible. Selecciona otra.',
    'booking.payment.authRequired': 'Inicia sesión para completar tu reserva.',

    // Confirmation
    'booking.confirmation.reservationId': 'ID de Reservación',
    'booking.confirmation.paymentMethod': 'Método de Pago',
    'booking.confirmation.viewAccount': 'Ver en Mi Cuenta',

    // Admin Panel
    'admin.title': 'Panel de Administración',
    'admin.heading': 'Administración',
    'admin.dashboard': 'Panel',
    'admin.reservations': 'Reservaciones',
    'admin.cruises': 'Cruceros',
    'admin.blog': 'Blog',
    'admin.logout': 'Cerrar Sesión',
    'admin.common.all': 'Todos',
    'admin.common.save': 'Guardar',
    'admin.common.cancel': 'Cancelar',
    'admin.common.edit': 'Editar',
    'admin.common.delete': 'Eliminar',
    'admin.common.view': 'Ver',
    'admin.common.actions': 'Acciones',
    'admin.common.loading': 'Cargando...',
    'admin.common.error': 'Error',
    'admin.dashboard.title': 'Panel de Control',
    'admin.dashboard.confirmedRevenue': 'Ingresos Confirmados',
    'admin.dashboard.pendingCount': 'Pendientes',
    'admin.dashboard.confirmedCount': 'Confirmadas',
    'admin.dashboard.revenueByCruise': 'Ingresos por Crucero',
    'admin.dashboard.confirmedReservations': 'Reservas Confirmadas',
    'admin.dashboard.totalGuests': 'Total Huéspedes',
    'admin.dashboard.revenue': 'Ingresos',
    'admin.dashboard.noCruiseData': 'No hay datos de ingresos aún',
    'admin.dashboard.error': 'Error al cargar el panel',
    'admin.reservations.title': 'Gestión de Reservaciones',
    'admin.reservations.empty': 'No hay reservaciones',
    'admin.reservations.filterStatus': 'Estado',
    'admin.reservations.id': 'ID',
    'admin.reservations.cruise': 'Crucero',
    'admin.reservations.date': 'Fecha',
    'admin.reservations.tier': 'Nivel',
    'admin.reservations.guests': 'Huéspedes',
    'admin.reservations.total': 'Total',
    'admin.reservations.status': 'Estado',
    'admin.reservations.approve': 'Aprobar',
    'admin.reservations.cancel': 'Cancelar',
    'admin.reservations.suspend': 'Suspender',
    'admin.reservationDetail.title': 'Detalle de Reservación',
    'admin.reservationDetail.subtitle': 'Información completa de la reservación',
    'admin.reservationDetail.id': 'ID de Reservación',
    'admin.reservationDetail.userId': 'ID de Usuario',
    'admin.reservationDetail.cruise': 'Crucero',
    'admin.reservationDetail.departureDate': 'Fecha de Salida',
    'admin.reservationDetail.route': 'Ruta',
    'admin.reservationDetail.tier': 'Nivel',
    'admin.reservationDetail.tierPrice': 'Precio por Nivel',
    'admin.reservationDetail.guestCount': 'Cantidad de Huéspedes',
    'admin.reservationDetail.totalAmount': 'Monto Total',
    'admin.reservationDetail.paymentMethod': 'Método de Pago',
    'admin.reservationDetail.createdAt': 'Fecha de Creación',
    'admin.reservationDetail.cruiseId': 'ID de Crucero',
    'admin.reservationDetail.notes': 'Notas',
    'admin.reservationDetail.notesPlaceholder': 'Nombres de la tripulación, anotaciones...',
    'admin.reservationDetail.notesHelp': 'Guarda notas sobre la reservación (tripulación, preferencias, etc.)',
    'admin.cruises.title': 'Gestión de Cruceros',
    'admin.cruises.empty': 'No hay cruceros',
    'admin.cruises.add': 'Agregar Crucero',
    'admin.cruises.edit': 'Editar Crucero',
    'admin.cruises.confirmDelete': '¿Eliminar este crucero?',
    'admin.cruise.name': 'Nombre',
    'admin.cruise.departureDate': 'Fecha de Salida',
    'admin.cruise.returnDate': 'Fecha de Regreso',
    'admin.cruise.route': 'Ruta',
    'admin.cruise.boat': 'Barco',
    'admin.cruise.dives': 'Inmersiones',
    'admin.cruise.basic': 'Básico',
    'admin.cruise.standard': 'Estándar',
    'admin.cruise.premium': 'Premium',
    'admin.cruise.status': 'Estado',
    'admin.cruise.active': 'Activo',
    'admin.cruise.inactive': 'Inactivo',
    'admin.cruise.namePlaceholder': 'ej. Socorro Islands',
    'admin.cruise.routePlaceholder': 'ej. Revillagigedo Archipelago',
    'admin.blog.title': 'Gestión de Blog',
    'admin.blog.empty': 'No hay publicaciones',
    'admin.blog.add': 'Agregar Publicación',
    'admin.blog.edit': 'Editar Publicación',
    'admin.blog.confirmDelete': '¿Eliminar esta publicación?',
    'admin.blog.fifoLabel': 'Publicaciones publicadas:',
    'admin.blog.titleCol': 'Título',
    'admin.blog.status': 'Estado',
    'admin.blog.createdAt': 'Fecha de Creación',
    'admin.blog.published': 'Publicada',
    'admin.blog.draft': 'Borrador',
    'admin.blog.formTitle': 'Título',
    'admin.blog.formTitlePlaceholder': 'Título de la publicación',
    'admin.blog.formContent': 'Contenido',
    'admin.blog.formContentPlaceholder': 'Contenido de la publicación...',
    'admin.blog.formImageUrl': 'URL de Imagen',
    'admin.blog.formStatus': 'Estado',
    'admin.blog.fifoWarning': 'Al publicar, si ya hay 5 publicaciones, la más antigua será eliminada automáticamente.',

    // Calendar
    'calendar.title': 'Calendario de Expediciones',
    'calendar.subtitle': 'Explora nuestras próximas salidas y encuentra tu próxima aventura',
    'calendar.available': 'Expedición Disponible',
    'calendar.noDates': 'No hay expediciones programadas en este momento. Vuelve pronto o contáctanos para próximas fechas.',
    'calendar.loading': 'Cargando calendario...',
    'calendar.error': 'No se pudieron cargar las expediciones. Intenta de nuevo.',
    'calendar.retry': 'Reintentar',
    'calendar.bookNow': 'Reservar Ahora',
    'calendar.dives': 'inmersiones',
    'calendar.from': 'Desde',
    'calendar.departs': 'Sale',
    'calendar.returns': 'Regresa',
    'calendar.days': 'días',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
